##
## EPITECH PROJECT, 2025
## Arcade
## File description:
## Makefile for all game libraries
##

all:
	$(MAKE) -C snake

clean:
	$(MAKE) -C snake clean

fclean:
	$(MAKE) -C snake fclean

re: fclean all

.PHONY: all clean fclean re
