##
## EPITECH PROJECT, 2025
## Arcade
## File description:
## Makefile for all graphics libraries
##

all:
	$(MAKE) -C sfml

clean:
	$(MAKE) -C sfml clean

fclean:
	$(MAKE) -C sfml fclean

re: fclean all

.PHONY: all clean fclean re
